package net.vurs.conn.sql.streamer.component;

import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;

import net.vurs.conn.sql.streamer.SQLPrimaryKeyStreamer;
import net.vurs.service.definition.EntityService;

public class IntegerStreamer extends SQLPrimaryKeyStreamer<Integer> {

	public IntegerStreamer(EntityService service, Class<Integer> type,
			ParameterizedType subType) {
		super(service, type, subType);
	}

	@Override
	public String write(Object comp, byte[] name, long ts) {
		return comp.toString();
	}

	@Override
	public String generateKey() {
		return ""; // this will get auto generated by the db
	}
	
	@Override
	public String generateColumnSchemaType(Field field) {
		return "INT(11)";
	}
	
	@Override
	public String generateColumnSchemaDefaultsAndConstraints(Field field) {
		return "DEFAULT 0";
	}

	@Override
	public String generateColumnSchemaPrimaryKeyModifier(Field field) {
		return String.format("AUTO_INCREMENT, PRIMARY KEY (`%s`)", field.getName());
	}

}
